"use strict";
let myGuset1 = ["Ali", "BooAli", "Adeel", "Liaqat Bhai", "Afzal", "Junaid"];
console.log(`${myGuset1[0]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[1]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[2]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[3]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[4]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[5]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`Suddenly ${myGuset1[5]} is not coming tonight. So, i,ve replace them another friend. `);
myGuset1[5] = "Ubaid Raza";
console.log(`${myGuset1[0]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[1]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[2]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[3]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[4]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset1[5]}, I've invited you to dinner at my home on 8PM tonight. `);
