"use strict";
let myGuset2 = ["Ali", "BooAli", "Adeel", "Liaqat Bhai", "Afzal", "Junaid"];
console.log(`${myGuset2[0]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[1]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[2]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[3]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[4]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[5]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`Suddenly ${myGuset2[5]} is not coming tonight. So, i,ve replace them another friend. `);
myGuset2[5] = "Ubaid Raza";
console.log(`${myGuset2[0]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[1]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[2]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[3]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[4]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[5]}, I've invited you to dinner at my home on 8PM tonight. `);
myGuset2.push("Hmaza", "Tamoor", "Faizan");
console.log(`${myGuset2[0]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[1]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[2]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[3]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[4]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[5]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[6]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[7]}, I've invited you to dinner at my home on 8PM tonight. `);
console.log(`${myGuset2[8]}, I've invited you to dinner at my home on 8PM tonight. `);
