"use strict";
let FavCity = ["Lahore", "Islamabad", "Karachi", "Toba", "Gojra"];
console.log(`Original Order :  ${FavCity}`);
console.log(`In alphabetical order :  ${FavCity.slice().sort()}`);
console.log(`Original Order :  ${FavCity}`);
console.log(`Reverse alphabetical order : ${FavCity.slice().sort().reverse()} \n`);
console.log(`Original Order :  ${FavCity}\n\n`);
FavCity.reverse();
console.log(`Reverse the order : ${FavCity}`);
FavCity.reverse();
console.log(`Original Order :  ${FavCity}`);
console.log(`In alphabetical order :  ${FavCity.slice().sort()}`);
console.log(`Reverse alphabetical order : ${FavCity.slice().sort().reverse()} `);
